### ISSUE TITLE
WIP: Treasury

### ISSUE THREAD

**Issue by MarekHauzr** [CarmineOptions/governance#45]
This issue is WIP and needs review!

Create a treasury smart contract within Carmine Governance.

It has to be a separate smart contract, the reason so that funds will be easily distinguishable from security pool (we will have that down the line).

The Treasury smart contract will be fully managed by the governance. Expect most of the work will happen in the Governance smart contracts.

Treasury will contain many different ERC20 tokens and has to be able to manage that.

Required features (standardized proposals):
- Send money to address (specify receiver address, amount, token) 
- Allow address to claim money (specify receiver address, amount, token)
- Allow treasury to provide liquidity to Carmine Options AMM liquidity pools, include withdraw functionality.

Feel free to comment on the expected proposals.

**Comment by Nonnyjoe** [comment]
I'll like to handle this @MarekHauzr
