### ISSUE TITLE
Rename CARM to veCARM

### ISSUE THREAD

**Issue by MarekHauzr** [CarmineOptions/governance#46]
Prepare a governance proposal that renames CARM to veCARM.

The goal is to allow for staking the Carmine token. The present day CARM (after this task is done and applied veCARM) is non-transferable, many users already have it and the token will become the staked one.

Issuance of new (transferable) token will be implemented in a separate github-issue.

**Comment by loubna-msellek** [comment]
Hi, I would like to try this issue and the issue 47

**Comment by MarekHauzr** [comment]
Hi, its yours. Could you share tg/discord handle so that we could discuss OnlyDust payment?

> Hi, I would like to try this issue and the issue 47

**Comment by MarekHauzr** [comment]
@loubna-msellek ping

**Comment by loubna-msellek** [comment]
Hi, of course ! Here is my discord : @loubnamsk

**Comment by tensojka** [comment]
> Hi, of course ! Here is my discord : @loubnamsk

Can't find you on Discord; maybe that's your display name not your username? Anyway, my Discord: `svetylko.` (there's a dot at the end) or Telegram: @svetylko

Looking forward to talking to you soon
