### ISSUE TITLE
Issue CARM token

### ISSUE THREAD

**Issue by MarekHauzr** [CarmineOptions/governance#47]
Carmine Options AMM DAO will allow for staking CARM token.

The process to get there is not a direct one, but it is not complicated.

This task assumes https://github.com/CarmineOptions/governance/issues/46 is already implemented and accepted by the governance.

The task is to prepare a governance proposal that will create and issue new ERC20 token, called CARM, with 100mil max supply, 18 deximals. Within the proposal the token will not only be issued, but it will also have governance smart contract to be set the owner and governance will be updated so that it can handle the potential upgrades of the new token.

**Comment by OkoliEvans** [comment]
I'd love to take on this

**Comment by MarekHauzr** [comment]
Great, could you share your discord/telegram handle? to discuss the onlydust rewards?

**Comment by tensojka** [comment]
@OkoliEvans pinged you on Telegram, please book a call with me so we can go through it

**Comment by nch7** [comment]
isn't CARM token deployed already? what will happen with the old contract?
